version: "3"

services:
    postgresdb:
        image: postgres
        restart: on-failure
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/database
        volumes:
            - ./app/db_data/postgres:/var/lib/postgresql/data/database
    phppgadmin:
        image: docker.io/bitnami/phppgadmin:7
        ports:
            - '5080:8080'
            - '50443:8443'
        environment:
            - DATABASE_HOST=postgresdb
        depends_on:
            - postgresdb
    couchdb:
        image: couchdb:3
        restart: on-failure
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
        volumes:
            - ./app/db_data/couchDB:/opt/couchdb/data
        ports:
            - "5984:5984"
    couchdb_initializer:
        image: curlimages/curl
        restart: on-failure
        depends_on:
            - couchdb
        command: ["sh","-c","sleep 15 && curl -u admin:password -X PUT couchdb:5984/_replicator && curl -u admin:password -X PUT couchdb:5984/_users && curl -u admin:password -X PUT couchdb:5984/_global_changes"]        
    frontend:
        build: ./src/microservices-frontend
        image: 127.0.0.1:5000/frontend
        restart: on-failure
        deploy:
            replicas: 1
    jwt:
        build: ./src/jwt_issuer_public/
        image: 127.0.0.1:5000/jwt
        restart: on-failure
        deploy:
            replicas: 1
        volumes:
            - ./app/certificates:/project/certs
        depends_on:
            - postgresdb
    images:
        build: ./src/node-image-compression/
        image: 127.0.0.1:5000/images
        restart: on-failure
        deploy:
            replicas: 1
        command: >
            bash -c "node index.js"
        depends_on:
            - jwt
            - couchdb_initializer
        volumes:
            - ./app/certificates:/usr/src/app/certificates
            - ./app/data/images_public:/usr/src/app/public_files
            - ./app/data/images_private:/usr/src/app/private_files
            - ./app/settings/image-compression:/usr/src/app/misc
    permissions:
        build: ./src/flask-permission-manager
        image: 127.0.0.1:5000/permissions
        restart: on-failure
        deploy:
            replicas: 1
        depends_on:
            - jwt
            - postgresdb
        volumes:
            - ./app/certificates:/project/certs
    proxy:
        build: ./src/microservice-reverse-proxy
        image: 127.0.0.1:5000/proxy
        restart: on-failure
        deploy:
            replicas: 1
        depends_on:
            - images
            - jwt
            - frontend
        volumes:
            - ./app/certificates:/etc/ssl/certs/
        ports: 
            - "8080:80"
            - "8443:443"